import type { Finding } from "./findings";
import { RationaleSchema, type RecommendationDraft } from "./rationale";
import { validateStrategyText } from "./validator";

/**
 * Rule-based generators: finding → full recommendation draft. Strategy-level ONLY;
 * every draft passes the product-reference validator or generation throws (a
 * generator emitting product advice is a bug, not a warning).
 * Every draft carries a FULL Hebrew rationale (rationaleHe) alongside the English one.
 */

type Generator = (f: Finding) => RecommendationDraft | null;

const severityConfidence = { WARNING: 80, NOTICE: 70, INFO: 60 } as const;

const GENERATORS: Record<string, Generator> = {
  LIQUIDITY_BELOW_TARGET: (f) => ({
    type: "INCREASE_LIQUIDITY",
    title: `Build the emergency fund up to ${f.metrics["targetMonths"]} months of expenses`,
    titleHe: `להשלים את קרן החירום ל-${f.metrics["targetMonths"]} חודשי הוצאה`,
    rationale: {
      why: `Liquid runway is ${f.metrics["runwayMonths"]} months against a target of ${f.metrics["targetMonths"]}; an income shock would force selling long-term holdings or taking expensive credit at the worst time.`,
      benefits: ["Shock absorption without forced sales", "Cheaper than emergency credit", "Reduces stress on every other financial decision"],
      risks: ["Cash held for safety lags inflation slightly"],
      tradeoffs: ["Money parked for emergencies is not compounding in long-term investments"],
      taxImplications: "None for holding liquid reserves; interest on deposits is taxable at the standard rate.",
      liquidityImplications: "Directly increases household liquidity.",
      timeHorizon: "SHORT",
      sensitivity: "Sensitive to the monthly-expense estimate; re-check after mapping all expense flows.",
      alternatives: ["A committed credit line as partial backstop (weaker: costs and can be withdrawn)", "Staggered bank deposits with laddered maturities"],
      expectedImpact: `Close a gap of roughly ${Number(f.metrics["targetMonths"]) - Number(f.metrics["runwayMonths"])} months of expenses in liquid reserves.`,
    },
    rationaleHe: {
      why: `הרזרבה הנזילה מכסה ${f.metrics["runwayMonths"]} חודשי הוצאה לעומת יעד של ${f.metrics["targetMonths"]}; זעזוע הכנסה יאלץ מכירת נכסים ארוכי-טווח או נטילת אשראי יקר בעיתוי הגרוע ביותר.`,
      benefits: ["ספיגת זעזועים ללא מכירות כפויות", "זול יותר מאשראי חירום", "מפחית לחץ מכל החלטה פיננסית אחרת"],
      risks: ["מזומן המוחזק לביטחון מפגר מעט אחרי האינפלציה"],
      tradeoffs: ["כסף שמיועד לחירום אינו צובר תשואה בהשקעות ארוכות-טווח"],
      taxImplications: "אין השלכת מס על עצם החזקת רזרבה נזילה; ריבית על פיקדונות חייבת במס בשיעור הרגיל.",
      liquidityImplications: "מגדיל ישירות את נזילות משק הבית.",
      timeHorizon: "SHORT",
      sensitivity: "רגיש לאומדן ההוצאה החודשית; יש לבדוק שוב לאחר מיפוי כל תזרימי ההוצאות.",
      alternatives: ["מסגרת אשראי מאושרת כגיבוי חלקי (חלש יותר: כרוכה בעלות ועלולה להתבטל)", "פיקדונות בנקאיים מדורגים עם מועדי פירעון שונים"],
      expectedImpact: `סגירת פער של כ-${Number(f.metrics["targetMonths"]) - Number(f.metrics["runwayMonths"])} חודשי הוצאה ברזרבה הנזילה.`,
    },
    subscores: { impact: 85, ease: 70, taxBenefit: 10, riskReduction: 90, goalContribution: 80, urgency: 85 },
    confidence: severityConfidence.WARNING,
    evidenceItemIds: f.evidenceItemIds,
    goalTypesImproved: ["EMERGENCY_FUND"],
    assumptionKeysUsed: ["emergency_fund_months"],
  }),

  EXCESS_IDLE_CASH: (f) => ({
    type: "REDUCE_IDLE_CASH",
    title: "Put idle cash beyond the emergency buffer to work",
    titleHe: "להעביר מזומן עודף מעבר לכרית הביטחון לאפיקים מניבים",
    rationale: {
      why: `Cash covering ${f.metrics["cashMonths"]} months of expenses sits idle versus a ${f.metrics["targetMonths"]}-month target; inflation erodes its real value every year.`,
      benefits: ["Restores long-term purchasing power", "Aligns allocation with household goals"],
      risks: ["Invested amounts fluctuate in value", "Timing of deployment affects short-term results"],
      tradeoffs: ["Less immediate liquidity beyond the retained buffer"],
      taxImplications: "Gains in taxable channels are subject to capital-gains tax; tax-advantaged wrappers may apply first (see separate recommendations).",
      liquidityImplications: "Keeps the full emergency buffer; only the excess is deployed.",
      timeHorizon: "MEDIUM",
      sensitivity: "Sensitive to the expense estimate and the emergency-fund target assumption.",
      alternatives: ["Gradual deployment over several months", "Short-term deposits as an interim step"],
      expectedImpact: "Excess cash begins compounding toward long-term goals instead of eroding.",
    },
    rationaleHe: {
      why: `מזומן בהיקף ${f.metrics["cashMonths"]} חודשי הוצאה שוכב ללא תשואה לעומת יעד של ${f.metrics["targetMonths"]} חודשים; האינפלציה שוחקת את ערכו הריאלי מדי שנה.`,
      benefits: ["משקם את כוח הקנייה ארוך-הטווח", "מיישר את הקצאת הנכסים עם יעדי משק הבית"],
      risks: ["סכומים מושקעים תנודתיים בערכם", "עיתוי הפריסה משפיע על התוצאות בטווח הקצר"],
      tradeoffs: ["פחות נזילות מיידית מעבר לכרית שנשמרת"],
      taxImplications: "רווחים באפיקים חייבים כפופים למס רווחי הון; ייתכן שכדאי קודם למצות עטיפות מוטבות-מס (ראו המלצות נפרדות).",
      liquidityImplications: "כרית החירום נשמרת במלואה; רק העודף מנותב להשקעה.",
      timeHorizon: "MEDIUM",
      sensitivity: "רגיש לאומדן ההוצאות ולהנחת יעד קרן החירום.",
      alternatives: ["פריסה הדרגתית על פני מספר חודשים", "פיקדונות קצרים כשלב ביניים"],
      expectedImpact: "המזומן העודף מתחיל לצבור תשואה לטובת היעדים ארוכי-הטווח במקום להישחק.",
    },
    subscores: { impact: 70, ease: 75, taxBenefit: 30, riskReduction: 20, goalContribution: 75, urgency: 40 },
    confidence: severityConfidence.NOTICE,
    evidenceItemIds: f.evidenceItemIds,
    goalTypesImproved: ["FINANCIAL_INDEPENDENCE", "RETIREMENT", "LIFESTYLE"],
    assumptionKeysUsed: ["emergency_fund_months", "expected_real_return_equity_pct", "inflation_il_pct"],
  }),

  CONCENTRATION_SINGLE_ASSET: (f) => ({
    type: "REDUCE_CONCENTRATION_RISK",
    title: `Reduce single-position concentration (${f.metrics["itemName"]})`,
    titleHe: `להקטין ריכוזיות בנכס בודד (${f.metrics["itemName"]})`,
    rationale: {
      why: `One position holds ${f.metrics["sharePct"]}% of household assets (threshold ${f.metrics["thresholdPct"]}%); an idiosyncratic shock to it would hit the whole household plan.`,
      benefits: ["Lower dependence on a single outcome", "Smoother long-term path toward goals"],
      risks: ["Realizing gains may trigger tax now rather than later"],
      tradeoffs: ["If the concentrated position outperforms, diversification lowers upside"],
      taxImplications: "Reducing a position can realize capital gains; spreading realization across tax years may soften the hit.",
      liquidityImplications: "Diversified holdings are typically easier to draw on gradually.",
      timeHorizon: "MEDIUM",
      sensitivity: "Depends on valuation freshness of the concentrated position.",
      alternatives: ["Divert only NEW savings elsewhere (slower, no tax event)", "Staged reduction over multiple years"],
      expectedImpact: `Bring the position below ${f.metrics["thresholdPct"]}% of household assets.`,
    },
    rationaleHe: {
      why: `פוזיציה אחת מרכזת ${f.metrics["sharePct"]}% מנכסי משק הבית (סף ${f.metrics["thresholdPct"]}%); זעזוע ייחודי בה יפגע בתוכנית של משק הבית כולו.`,
      benefits: ["תלות נמוכה יותר בתוצאה בודדת", "מסלול חלק יותר בדרך אל היעדים"],
      risks: ["מימוש רווחים עשוי להקדים את אירוע המס"],
      tradeoffs: ["אם הפוזיציה המרוכזת תניב ביצועי-יתר, הפיזור מקטין את פוטנציאל הרווח"],
      taxImplications: "הקטנת פוזיציה עשויה לממש רווחי הון; פריסת המימוש על פני שנות מס עשויה לרכך את הפגיעה.",
      liquidityImplications: "החזקות מפוזרות קלות בדרך כלל למשיכה הדרגתית.",
      timeHorizon: "MEDIUM",
      sensitivity: "תלוי בטריות השווי של הפוזיציה המרוכזת.",
      alternatives: ["ניתוב חיסכון חדש בלבד לאפיקים אחרים (איטי יותר, ללא אירוע מס)", "הקטנה מדורגת על פני מספר שנים"],
      expectedImpact: `להוריד את הפוזיציה אל מתחת ל-${f.metrics["thresholdPct"]}% מנכסי משק הבית.`,
    },
    subscores: { impact: 80, ease: 50, taxBenefit: 0, riskReduction: 85, goalContribution: 60, urgency: 55 },
    confidence: severityConfidence.WARNING,
    evidenceItemIds: f.evidenceItemIds,
    goalTypesImproved: ["FINANCIAL_INDEPENDENCE", "RETIREMENT"],
    assumptionKeysUsed: ["concentration_single_asset_max_pct"],
  }),

  CONCENTRATION_INSTITUTION: (f) => ({
    type: "REDUCE_INSTITUTION_CONCENTRATION",
    title: `Spread holdings across managing institutions (${f.metrics["institution"]})`,
    titleHe: `לפזר החזקות בין גופים מנהלים (${f.metrics["institution"]})`,
    rationale: {
      why: `${f.metrics["sharePct"]}% of assets sit with one institution; operational issues, fee drift, or service degradation there affect most of the household at once.`,
      benefits: ["Operational resilience", "Better fee-negotiation position"],
      risks: ["More accounts to track"],
      tradeoffs: ["Some institutions give scale discounts that splitting forfeits"],
      taxImplications: "Transfers between managers of the same wrapper type are typically not tax events in Israel.",
      liquidityImplications: "Neutral.",
      timeHorizon: "LONG",
      sensitivity: "Low; based on current custodial distribution.",
      alternatives: ["Keep concentration but negotiate fees with scale", "Split only new contributions"],
      expectedImpact: "No single institution manages a majority of household assets.",
    },
    rationaleHe: {
      why: `${f.metrics["sharePct"]}% מהנכסים מנוהלים בגוף אחד; תקלה תפעולית, זחילת דמי ניהול או ירידה בשירות אצלו משפיעות בבת אחת על רוב משק הבית.`,
      benefits: ["חוסן תפעולי", "עמדת מיקוח טובה יותר על דמי ניהול"],
      risks: ["יותר חשבונות למעקב"],
      tradeoffs: ["חלק מהגופים מעניקים הנחות היקף שהפיצול מוותר עליהן"],
      taxImplications: "ניוד בין גופים מנהלים באותו סוג עטיפה אינו בדרך כלל אירוע מס בישראל.",
      liquidityImplications: "ניטרלי.",
      timeHorizon: "LONG",
      sensitivity: "נמוכה; מבוסס על פיזור ההחזקות הנוכחי בין הגופים.",
      alternatives: ["לשמור על הריכוזיות אך למנף אותה למיקוח על דמי הניהול", "לפצל הפקדות חדשות בלבד"],
      expectedImpact: "אף גוף מנהל בודד לא ינהל את רוב נכסי משק הבית.",
    },
    subscores: { impact: 40, ease: 60, taxBenefit: 0, riskReduction: 55, goalContribution: 20, urgency: 20 },
    confidence: severityConfidence.NOTICE,
    evidenceItemIds: f.evidenceItemIds,
    goalTypesImproved: [],
    assumptionKeysUsed: ["concentration_institution_max_pct"],
  }),

  CURRENCY_HOME_BIAS: (f) => ({
    type: "IMPROVE_GEO_DIVERSIFICATION",
    title: "Add foreign-currency / global exposure",
    titleHe: "להוסיף חשיפה גלובלית ומטבעית",
    rationale: {
      why: `Only ${f.metrics["foreignPct"]}% of assets are outside ${f.metrics["baseCurrency"]}; household income, property, and savings all depend on one economy and currency.`,
      benefits: ["Cushions local-economy and currency shocks", "Access to global growth"],
      risks: ["Exchange-rate swings add short-term volatility"],
      tradeoffs: ["Foreign holdings complicate tax reporting slightly"],
      taxImplications: "Foreign income/gains are taxable in Israel; wrappers differ in withholding treatment.",
      liquidityImplications: "Neutral to positive; global markets are deep.",
      timeHorizon: "LONG",
      sensitivity: `Sensitive to the ${f.metrics["minPct"]}% minimum-exposure assumption — adjust it to your comfort.`,
      alternatives: ["Increase gradually via new contributions only", "Currency exposure without asset exposure (weaker diversification)"],
      expectedImpact: `Raise foreign exposure toward at least ${f.metrics["minPct"]}% of assets.`,
    },
    rationaleHe: {
      why: `רק ${f.metrics["foreignPct"]}% מהנכסים נמצאים מחוץ ל-${f.metrics["baseCurrency"]}; ההכנסה, הנדל"ן והחיסכון של משק הבית תלויים כולם בכלכלה אחת ובמטבע אחד.`,
      benefits: ["ריכוך זעזועים של הכלכלה המקומית והמטבע", "גישה לצמיחה הגלובלית"],
      risks: ["תנודות שער החליפין מוסיפות תנודתיות בטווח הקצר"],
      tradeoffs: ["החזקות זרות מסבכות מעט את הדיווח למס"],
      taxImplications: "הכנסות ורווחים מחו\"ל חייבים במס בישראל; עטיפות שונות נבדלות בטיפול בניכוי במקור.",
      liquidityImplications: "ניטרלי עד חיובי; השווקים הגלובליים עמוקים ונזילים.",
      timeHorizon: "LONG",
      sensitivity: `רגיש להנחת החשיפה המינימלית של ${f.metrics["minPct"]}% — התאימו אותה לרמת הנוחות שלכם.`,
      alternatives: ["הגדלה הדרגתית דרך הפקדות חדשות בלבד", "חשיפה מטבעית ללא חשיפת נכסים (פיזור חלש יותר)"],
      expectedImpact: `העלאת החשיפה הזרה לכיוון ${f.metrics["minPct"]}% מהנכסים לפחות.`,
    },
    subscores: { impact: 65, ease: 65, taxBenefit: 0, riskReduction: 70, goalContribution: 50, urgency: 30 },
    confidence: severityConfidence.NOTICE,
    evidenceItemIds: f.evidenceItemIds,
    goalTypesImproved: ["FINANCIAL_INDEPENDENCE", "RETIREMENT"],
    assumptionKeysUsed: ["currency_foreign_min_pct"],
  }),

  CURRENCY_FOREIGN_EXCESS: (f) => ({
    type: "REBALANCE_CURRENCY_EXPOSURE",
    title: "Trim excess foreign-currency exposure",
    titleHe: "לאזן חשיפה מטבעית עודפת",
    rationale: {
      why: `${f.metrics["foreignPct"]}% of assets are in foreign currency against a ${f.metrics["maxPct"]}% ceiling, while household expenses are in the base currency — a strong shekel squeezes the plan.`,
      benefits: ["Better match between assets and future expenses"],
      risks: ["Conversion locks in current exchange rates"],
      tradeoffs: ["Less upside if the shekel weakens"],
      taxImplications: "Currency conversion itself is not a tax event; realizing gains may be.",
      liquidityImplications: "Neutral.",
      timeHorizon: "MEDIUM",
      sensitivity: "Sensitive to the ceiling assumption and to expected future expense currency mix.",
      alternatives: ["Rebalance via new savings only", "Partial currency hedging"],
      expectedImpact: `Bring foreign exposure under ${f.metrics["maxPct"]}%.`,
    },
    rationaleHe: {
      why: `${f.metrics["foreignPct"]}% מהנכסים מוחזקים במטבע זר לעומת תקרה של ${f.metrics["maxPct"]}%, בעוד הוצאות משק הבית במטבע הבסיס — שקל חזק לוחץ על התוכנית.`,
      benefits: ["התאמה טובה יותר בין הנכסים להוצאות העתידיות"],
      risks: ["המרה נועלת את שערי החליפין הנוכחיים"],
      tradeoffs: ["פחות פוטנציאל רווח אם השקל ייחלש"],
      taxImplications: "המרת מטבע כשלעצמה אינה אירוע מס; מימוש רווחים עשוי להיות.",
      liquidityImplications: "ניטרלי.",
      timeHorizon: "MEDIUM",
      sensitivity: "רגיש להנחת התקרה ולתמהיל המטבעי הצפוי של ההוצאות בעתיד.",
      alternatives: ["איזון דרך חיסכון חדש בלבד", "גידור מטבעי חלקי"],
      expectedImpact: `הורדת החשיפה הזרה אל מתחת ל-${f.metrics["maxPct"]}%.`,
    },
    subscores: { impact: 55, ease: 60, taxBenefit: 0, riskReduction: 60, goalContribution: 40, urgency: 30 },
    confidence: severityConfidence.NOTICE,
    evidenceItemIds: f.evidenceItemIds,
    goalTypesImproved: [],
    assumptionKeysUsed: ["currency_foreign_max_pct"],
  }),

  TAX_HISHTALMUT_MISSING: (f) => ({
    type: "INCREASE_TAX_ADVANTAGED_SAVINGS",
    title: `Open/renew a keren hishtalmut for ${f.metrics["memberName"]}`,
    titleHe: `לפתוח/לחדש קרן השתלמות עבור ${f.metrics["memberName"]}`,
    rationale: {
      why: `No keren hishtalmut is mapped for ${f.metrics["memberName"]}. It is Israel's only fully capital-gains-exempt medium-term vehicle (exempt deposit ceiling ₪${f.metrics["exemptCeilingAnnualILS"]}/year).`,
      benefits: ["Capital-gains exemption on qualifying deposits", "Employer-matched contributions for employees", "Liquid after 6 years"],
      risks: ["Funds are locked for the vesting period"],
      tradeoffs: ["Contributions reduce take-home pay today"],
      taxImplications: "Deposits within the ceiling grow and are withdrawn tax-free after vesting; employer contributions within limits are not taxed as salary.",
      liquidityImplications: "Locked ~6 years, then fully liquid — plan the emergency fund separately.",
      timeHorizon: "IMMEDIATE",
      sensitivity: "Ceilings are year-specific (see TaxRegistry, pending owner review).",
      alternatives: ["Gemel lehashkaa (liquid anytime, taxed at withdrawal)", "Taxable saving (no exemption)"],
      expectedImpact: "Capture the annual exempt ceiling for this member from now on — compounding tax-free.",
    },
    rationaleHe: {
      why: `לא ממופה קרן השתלמות עבור ${f.metrics["memberName"]}. זהו האפיק היחיד בישראל עם פטור מלא ממס רווחי הון לטווח בינוני (תקרת הפקדה פטורה של ₪${f.metrics["exemptCeilingAnnualILS"]} בשנה).`,
      benefits: ["פטור ממס רווחי הון על הפקדות בגובה התקרה", "הפרשות מקבילות מהמעסיק לשכירים", "נזילות מלאה אחרי 6 שנים"],
      risks: ["הכספים נעולים בתקופת הוותק"],
      tradeoffs: ["ההפקדות מקטינות את השכר הפנוי היום"],
      taxImplications: "הפקדות בתוך התקרה צוברות ונמשכות בפטור ממס לאחר הוותק; הפרשות מעסיק במסגרת התקרות אינן ממוסות כשכר.",
      liquidityImplications: "נעולה כ-6 שנים ולאחר מכן נזילה במלואה — יש לתכנן את קרן החירום בנפרד.",
      timeHorizon: "IMMEDIATE",
      sensitivity: "התקרות תלויות שנת מס (ראו רישום המס — ממתין לאישור הבעלים).",
      alternatives: ["גמל להשקעה (נזיל בכל עת, ממוסה במשיכה)", "חיסכון חייב במס (ללא פטור)"],
      expectedImpact: "מיצוי התקרה הפטורה השנתית עבור בן/בת הבית מעתה ואילך — צבירה פטורה ממס.",
    },
    subscores: { impact: 75, ease: 85, taxBenefit: 95, riskReduction: 10, goalContribution: 65, urgency: 60 },
    confidence: severityConfidence.NOTICE,
    evidenceItemIds: f.evidenceItemIds,
    goalTypesImproved: ["FINANCIAL_INDEPENDENCE", "CHILDREN_EDUCATION"],
    assumptionKeysUsed: [],
  }),

  TAX_PENSION_MISSING: (f) => ({
    type: "INCREASE_RETIREMENT_ALLOCATION",
    title: `Establish pension coverage for ${f.metrics["memberName"]}`,
    titleHe: `להסדיר כיסוי פנסיוני עבור ${f.metrics["memberName"]}`,
    rationale: {
      why: `No pension vehicle is mapped for ${f.metrics["memberName"]} — the household's retirement leg and its embedded disability/survivor insurance are missing for this member.`,
      benefits: ["Tax-deductible/credited contributions (sections 45a/47)", "Embedded disability and survivor coverage", "Compounding toward retirement"],
      risks: ["Locked until retirement age except in hardship tracks"],
      tradeoffs: ["Less flexible than taxable savings"],
      taxImplications: "Contributions enjoy deduction and credit benefits up to registry ceilings; growth is tax-deferred.",
      liquidityImplications: "Illiquid until retirement — size other buffers accordingly.",
      timeHorizon: "IMMEDIATE",
      sensitivity: "Benefit size depends on income level vs registry ceilings.",
      alternatives: ["IRA-style self-managed gemel for the investment leg (insurance handled separately)"],
      expectedImpact: "Retirement compounding plus insurance coverage begins for this member.",
    },
    rationaleHe: {
      why: `לא ממופה אפיק פנסיוני עבור ${f.metrics["memberName"]} — רגל הפרישה של משק הבית והכיסויים המובנים לאובדן כושר עבודה ושארים חסרים עבור בן/בת בית זה.`,
      benefits: ["הפקדות מזכות בניכוי ובזיכוי מס (סעיפים 45א/47)", "כיסוי מובנה לאובדן כושר עבודה ושארים", "צבירה מתמשכת לקראת פרישה"],
      risks: ["נעול עד גיל הפרישה למעט מסלולי חריגים"],
      tradeoffs: ["גמיש פחות מחיסכון חייב במס"],
      taxImplications: "ההפקדות נהנות מהטבות ניכוי וזיכוי עד תקרות הרישום; הצבירה בדחיית מס.",
      liquidityImplications: "לא נזיל עד הפרישה — יש לגדר כריות ביטחון אחרות בהתאם.",
      timeHorizon: "IMMEDIATE",
      sensitivity: "גובה ההטבה תלוי ברמת ההכנסה מול תקרות הרישום.",
      alternatives: ["גמל בניהול אישי (בסגנון IRA) לרגל ההשקעה (הביטוח מטופל בנפרד)"],
      expectedImpact: "צבירה פנסיונית וכיסוי ביטוחי מתחילים לפעול עבור בן/בת בית זה.",
    },
    subscores: { impact: 90, ease: 75, taxBenefit: 90, riskReduction: 75, goalContribution: 90, urgency: 80 },
    confidence: severityConfidence.WARNING,
    evidenceItemIds: f.evidenceItemIds,
    goalTypesImproved: ["RETIREMENT"],
    assumptionKeysUsed: [],
  }),

  HIGH_MANAGEMENT_FEE: (f) => ({
    type: "REDUCE_FEE_DRAG",
    title: `Negotiate or move: ${f.metrics["feePct"]}% fee on ${f.metrics["itemName"]}`,
    titleHe: `להוזיל דמי ניהול: ${f.metrics["feePct"]}% על ${f.metrics["itemName"]}`,
    rationale: {
      why: `Management fee of ${f.metrics["feePct"]}% exceeds the ${f.metrics["noticePct"]}% notice level; over decades fee drag compounds into a large share of the final balance.`,
      benefits: ["Every basis point saved compounds for you instead of the manager"],
      risks: ["None material; transfers between same-type wrappers preserve rights"],
      tradeoffs: ["Negotiation/transfer takes some effort"],
      taxImplications: "Same-wrapper transfers are not tax events in Israel.",
      liquidityImplications: "None.",
      timeHorizon: "SHORT",
      sensitivity: "Savings scale with balance and remaining horizon.",
      alternatives: ["Fee negotiation with the current manager", "Transfer to a lower-fee manager of the same product type"],
      expectedImpact: "Reduce annual fee drag on this account toward market-typical levels.",
    },
    rationaleHe: {
      why: `דמי ניהול של ${f.metrics["feePct"]}% חורגים מרף ההתראה של ${f.metrics["noticePct"]}%; לאורך עשורים גרירת דמי הניהול מצטברת לנתח גדול מהצבירה הסופית.`,
      benefits: ["כל נקודת בסיס שנחסכת נצברת עבורכם ולא עבור הגוף המנהל"],
      risks: ["אין סיכון מהותי; ניוד בין עטיפות מאותו סוג משמר זכויות"],
      tradeoffs: ["משא ומתן או ניוד דורשים מאמץ מסוים"],
      taxImplications: "ניוד בתוך אותו סוג עטיפה אינו אירוע מס בישראל.",
      liquidityImplications: "אין.",
      timeHorizon: "SHORT",
      sensitivity: "החיסכון גדל עם היתרה ועם אופק הזמן שנותר.",
      alternatives: ["משא ומתן על דמי הניהול מול הגוף הנוכחי", "ניוד לגוף מנהל זול יותר מאותו סוג מוצר"],
      expectedImpact: "הקטנת גרירת דמי הניהול השנתית בחשבון זה לכיוון הרמות המקובלות בשוק.",
    },
    subscores: { impact: 60, ease: 80, taxBenefit: 20, riskReduction: 10, goalContribution: 50, urgency: 40 },
    confidence: severityConfidence.NOTICE,
    evidenceItemIds: f.evidenceItemIds,
    goalTypesImproved: ["RETIREMENT", "FINANCIAL_INDEPENDENCE"],
    assumptionKeysUsed: ["management_fee_notice_pct", "management_fee_notice_by_type"],
  }),

  MORTGAGE_CPI_CONCENTRATION: (f) => ({
    type: "RESTRUCTURE_MORTGAGE_MIX",
    title: `Review CPI-linked share of the mortgage (${f.metrics["cpiSharePct"]}%)`,
    titleHe: `לבחון את רכיב ההצמדה במשכנתא (${f.metrics["cpiSharePct"]}%)`,
    rationale: {
      why: `${f.metrics["cpiSharePct"]}% of the mortgage principal is CPI-linked (threshold ${f.metrics["thresholdPct"]}%); sustained inflation raises both principal and payments simultaneously.`,
      benefits: ["Caps inflation pass-through into household debt", "More predictable payments"],
      risks: ["Unlinked tracks usually carry higher nominal rates", "Early-repayment fees may apply"],
      tradeoffs: ["Paying certainty premium vs keeping cheaper-but-linked debt"],
      taxImplications: "None directly.",
      liquidityImplications: "Refinancing costs cash up front (fees, appraisal).",
      timeHorizon: "MEDIUM",
      sensitivity: "Highly sensitive to the inflation assumption and remaining term.",
      alternatives: ["Partial early repayment of linked tracks specifically", "Wait for a favorable refinance window"],
      expectedImpact: `Bring the CPI-linked share below ${f.metrics["thresholdPct"]}% of principal.`,
    },
    rationaleHe: {
      why: `${f.metrics["cpiSharePct"]}% מקרן המשכנתא צמודי מדד (סף ${f.metrics["thresholdPct"]}%); אינפלציה מתמשכת מעלה בו-זמנית גם את הקרן וגם את ההחזר החודשי.`,
      benefits: ["תוחם את חלחול האינפלציה אל חוב משק הבית", "החזרים צפויים יותר"],
      risks: ["מסלולים לא-צמודים נושאים בדרך כלל ריבית נומינלית גבוהה יותר", "ייתכנו עמלות פירעון מוקדם"],
      tradeoffs: ["תשלום פרמיית ודאות לעומת שמירת חוב זול-אך-צמוד"],
      taxImplications: "אין השלכה ישירה.",
      liquidityImplications: "מיחזור דורש מזומן מראש (עמלות, שמאות).",
      timeHorizon: "MEDIUM",
      sensitivity: "רגיש מאוד להנחת האינפלציה וליתרת תקופת ההלוואה.",
      alternatives: ["פירעון מוקדם חלקי של המסלולים הצמודים דווקא", "המתנה לחלון מיחזור נוח"],
      expectedImpact: `הורדת הרכיב הצמוד אל מתחת ל-${f.metrics["thresholdPct"]}% מהקרן.`,
    },
    subscores: { impact: 65, ease: 40, taxBenefit: 0, riskReduction: 70, goalContribution: 35, urgency: 35 },
    confidence: severityConfidence.NOTICE,
    evidenceItemIds: f.evidenceItemIds,
    goalTypesImproved: [],
    assumptionKeysUsed: ["mortgage_cpi_linked_max_pct", "inflation_il_pct"],
  }),

  MORTGAGE_EXPENSIVE_TRACK: (f) => ({
    type: "ACCELERATE_DEBT_REPAYMENT",
    title: `Target the expensive mortgage track first (${f.metrics["maxRatePct"]}%)`,
    titleHe: `לטפל קודם במסלול המשכנתא היקר (${f.metrics["maxRatePct"]}%)`,
    rationale: {
      why: `A mortgage track carries ${f.metrics["maxRatePct"]}% — repaying it is a guaranteed, risk-free "return" at that rate, likely above expected investment returns.`,
      benefits: ["Guaranteed saving equal to the interest rate", "Lower monthly obligations"],
      risks: ["Uses liquidity that may be needed elsewhere"],
      tradeoffs: ["Early-repayment fees can offset part of the gain — check the schedule"],
      taxImplications: "None.",
      liquidityImplications: "Reduces liquid reserves by the repaid amount.",
      timeHorizon: "SHORT",
      sensitivity: "Compare against the expected-return assumption and any early-repayment fee.",
      alternatives: ["Refinance the track instead of repaying", "Split: partial repayment + keep buffer"],
      expectedImpact: "Interest saved at the track's full rate on every shekel repaid early.",
    },
    rationaleHe: {
      why: `מסלול משכנתא נושא ריבית של ${f.metrics["maxRatePct"]}% — פירעונו הוא "תשואה" מובטחת וחסרת סיכון בגובה הריבית, ככל הנראה מעל התשואה הצפויה מהשקעות.`,
      benefits: ["חיסכון מובטח בגובה הריבית", "התחייבויות חודשיות נמוכות יותר"],
      risks: ["משתמש בנזילות שאולי תידרש במקום אחר"],
      tradeoffs: ["עמלות פירעון מוקדם עשויות לקזז חלק מהרווח — יש לבדוק את לוח הסילוקין"],
      taxImplications: "אין.",
      liquidityImplications: "מקטין את הרזרבה הנזילה בגובה הסכום הנפרע.",
      timeHorizon: "SHORT",
      sensitivity: "יש להשוות מול הנחת התשואה הצפויה ומול עמלת פירעון מוקדם אם קיימת.",
      alternatives: ["מיחזור המסלול במקום פירעונו", "פיצול: פירעון חלקי תוך שמירת כרית ביטחון"],
      expectedImpact: "חיסכון בריבית בגובה הריבית המלאה של המסלול על כל שקל שנפרע מוקדם.",
    },
    subscores: { impact: 70, ease: 55, taxBenefit: 0, riskReduction: 60, goalContribution: 45, urgency: 50 },
    confidence: severityConfidence.NOTICE,
    evidenceItemIds: f.evidenceItemIds,
    goalTypesImproved: [],
    assumptionKeysUsed: ["expected_real_return_equity_pct", "expensive_debt_rate_pct"],
  }),

  ALLOCATION_GROWTH_BELOW_TARGET: (f) => ({
    type: "INCREASE_GROWTH_ALLOCATION",
    title: `Raise the growth share toward the ${f.metrics["targetPct"]}% target (now ${f.metrics["currentPct"]}%)`,
    titleHe: `להעלות את רכיב הצמיחה לכיוון היעד של ${f.metrics["targetPct"]}% (כיום ${f.metrics["currentPct"]}%)`,
    rationale: {
      why: `The household's growth share is ${f.metrics["currentPct"]}% of investable assets against a risk-derived target of ${f.metrics["targetPct"]}% (band ±${f.metrics["bandPct"]} points). With a ${f.metrics["horizonYears"]}-year horizon, a too-defensive mix sacrifices long-term compounding the plan relies on.`,
      benefits: ["Aligns the portfolio with the household's own risk answers and horizon", "Restores expected long-term growth toward goals"],
      risks: ["Higher short-term fluctuation in portfolio value"],
      tradeoffs: ["Larger temporary drawdowns in bad markets in exchange for higher expected outcomes"],
      taxImplications: "Shifting inside tax-advantaged wrappers (track changes) is not a tax event in Israel; shifts in taxable accounts may realize gains.",
      liquidityImplications: "Neutral — growth allocations remain sellable; the emergency buffer is handled separately.",
      timeHorizon: "MEDIUM",
      sensitivity: `Directly driven by the three risk-questionnaire assumptions and the ±${f.metrics["bandPct"]}-point band — update the questionnaire and the target moves with it.`,
      alternatives: ["Shift gradually via new contributions only (slower, no realization)", "Adjust investment tracks inside existing wrappers first (no tax event)"],
      expectedImpact: `Move roughly ${f.metrics["shiftBase"]} (base currency) from defensive to growth channels to close a ${f.metrics["gapPct"]}-point gap.`,
    },
    rationaleHe: {
      why: `רכיב הצמיחה של משק הבית עומד על ${f.metrics["currentPct"]}% מהנכסים ההשקעתיים לעומת יעד נגזר-סיכון של ${f.metrics["targetPct"]}% (רצועה ±${f.metrics["bandPct"]} נק'). עם אופק של ${f.metrics["horizonYears"]} שנים, תמהיל סולידי מדי מוותר על צבירה ארוכת-טווח שהתוכנית נשענת עליה.`,
      benefits: ["מיישר את התיק עם תשובות הסיכון והאופק של משק הבית עצמו", "משיב את פוטנציאל הצמיחה ארוך-הטווח לעבר היעדים"],
      risks: ["תנודתיות גבוהה יותר בשווי התיק בטווח הקצר"],
      tradeoffs: ["ירידות ערך זמניות גדולות יותר בשווקים קשים בתמורה לתוחלת תוצאה גבוהה יותר"],
      taxImplications: "שינוי מסלול בתוך עטיפות מוטבות-מס אינו אירוע מס בישראל; שינויים בחשבונות חייבים עשויים לממש רווחים.",
      liquidityImplications: "ניטרלי — רכיבי הצמיחה נשארים סחירים; כרית החירום מטופלת בנפרד.",
      timeHorizon: "MEDIUM",
      sensitivity: `נגזר ישירות משלוש הנחות שאלון הסיכון ומהרצועה של ±${f.metrics["bandPct"]} נק' — עדכון השאלון מזיז את היעד בהתאם.`,
      alternatives: ["מעבר הדרגתי דרך הפקדות חדשות בלבד (איטי יותר, ללא מימוש)", "התאמת מסלולי השקעה בתוך העטיפות הקיימות קודם (ללא אירוע מס)"],
      expectedImpact: `להעביר כ-${f.metrics["shiftBase"]} (במטבע הבסיס) מאפיקים סולידיים לאפיקי צמיחה לסגירת פער של ${f.metrics["gapPct"]} נק'.`,
    },
    subscores: { impact: 85, ease: 60, taxBenefit: 10, riskReduction: 30, goalContribution: 90, urgency: 55 },
    confidence: severityConfidence.WARNING,
    evidenceItemIds: f.evidenceItemIds,
    goalTypesImproved: ["RETIREMENT", "FINANCIAL_INDEPENDENCE", "CHILDREN_EDUCATION"],
    assumptionKeysUsed: ["risk_loss_tolerance", "risk_income_stability", "risk_horizon_years", "allocation_rebalance_band_pct"],
  }),

  ALLOCATION_GROWTH_ABOVE_TARGET: (f) => ({
    type: "REDUCE_GROWTH_ALLOCATION",
    title: `Trim the growth share toward the ${f.metrics["targetPct"]}% target (now ${f.metrics["currentPct"]}%)`,
    titleHe: `למתן את רכיב הצמיחה לכיוון היעד של ${f.metrics["targetPct"]}% (כיום ${f.metrics["currentPct"]}%)`,
    rationale: {
      why: `The growth share is ${f.metrics["currentPct"]}% of investable assets against a risk-derived target of ${f.metrics["targetPct"]}% (band ±${f.metrics["bandPct"]} points). The portfolio carries more fluctuation risk than the household's own answers say it is willing to bear.`,
      benefits: ["Reduces drawdown risk to the level the household chose", "Protects near-term goals from market swings"],
      risks: ["Lower expected long-term return after the shift"],
      tradeoffs: ["Giving up some upside for stability"],
      taxImplications: "Prefer shifting inside tax-advantaged wrappers first (track changes, no tax event); taxable-account sales may realize gains — consider spreading across tax years.",
      liquidityImplications: "Neutral to positive — defensive channels are typically highly liquid.",
      timeHorizon: "SHORT",
      sensitivity: `Driven by the risk-questionnaire assumptions and the ±${f.metrics["bandPct"]}-point band.`,
      alternatives: ["Direct all NEW savings to defensive channels (no realization)", "Rebalance inside wrappers via track changes first"],
      expectedImpact: `Move roughly ${f.metrics["shiftBase"]} (base currency) from growth to defensive channels to close a ${f.metrics["gapPct"]}-point gap.`,
    },
    rationaleHe: {
      why: `רכיב הצמיחה עומד על ${f.metrics["currentPct"]}% מהנכסים ההשקעתיים לעומת יעד נגזר-סיכון של ${f.metrics["targetPct"]}% (רצועה ±${f.metrics["bandPct"]} נק'). התיק נושא יותר סיכון תנודתיות ממה שמשק הבית עצמו הצהיר שהוא מוכן לשאת.`,
      benefits: ["מוריד את סיכון ירידות הערך לרמה שמשק הבית בחר", "מגן על יעדים קרובים מתנודות שוק"],
      risks: ["תוחלת תשואה ארוכת-טווח נמוכה יותר לאחר ההתאמה"],
      tradeoffs: ["ויתור על חלק מפוטנציאל הרווח בתמורה ליציבות"],
      taxImplications: "עדיף להתחיל בשינוי בתוך עטיפות מוטבות-מס (שינוי מסלול, ללא אירוע מס); מכירות בחשבונות חייבים עשויות לממש רווחים — שקלו פריסה בין שנות מס.",
      liquidityImplications: "ניטרלי עד חיובי — אפיקים סולידיים נזילים בדרך כלל.",
      timeHorizon: "SHORT",
      sensitivity: `נגזר מהנחות שאלון הסיכון ומהרצועה של ±${f.metrics["bandPct"]} נק'.`,
      alternatives: ["ניתוב כל החיסכון החדש לאפיקים סולידיים (ללא מימוש)", "איזון בתוך העטיפות דרך שינוי מסלול קודם"],
      expectedImpact: `להעביר כ-${f.metrics["shiftBase"]} (במטבע הבסיס) מאפיקי צמיחה לאפיקים סולידיים לסגירת פער של ${f.metrics["gapPct"]} נק'.`,
    },
    subscores: { impact: 75, ease: 60, taxBenefit: 0, riskReduction: 85, goalContribution: 60, urgency: 50 },
    confidence: severityConfidence.WARNING,
    evidenceItemIds: f.evidenceItemIds,
    goalTypesImproved: ["EMERGENCY_FUND", "LIFESTYLE"],
    assumptionKeysUsed: ["risk_loss_tolerance", "risk_income_stability", "risk_horizon_years", "allocation_rebalance_band_pct"],
  }),

  ALLOCATION_MIX_UNKNOWN: (f) => ({
    type: "COMPLETE_ALLOCATION_DATA",
    title: `Record the growth share for ${f.metrics["unknownCount"]} account(s) (${f.metrics["unknownSharePct"]}% of investable value)`,
    titleHe: `להזין רכיב צמיחה עבור ${f.metrics["unknownCount"]} חשבונות (${f.metrics["unknownSharePct"]}% מהשווי ההשקעתי)`,
    rationale: {
      why: `${f.metrics["unknownCount"]} account(s) (${f.metrics["itemNames"]}) have no growth-share figure, covering ${f.metrics["unknownSharePct"]}% of investable value. WealthOS never guesses what is inside a wrapper — until the mix is recorded, allocation advice is partial${Number(f.metrics["unknownSharePct"]) > Number(f.metrics["maxPct"]) ? " and the growth-vs-target comparison is REFUSED" : ""}.`,
      benefits: ["Unlocks (or sharpens) the allocation recommendation", "One-time data entry per account, editable any time"],
      risks: ["None — this is a data-completeness step, not an investment change"],
      tradeoffs: ["A few minutes of reading account statements to find each track's composition"],
      taxImplications: "None.",
      liquidityImplications: "None.",
      timeHorizon: "IMMEDIATE",
      sensitivity: "The account statement or the managing body's site lists each track's asset composition.",
      alternatives: ["Leave unknown — allocation analysis stays partial and conservative"],
      expectedImpact: "The allocation engine can compare the full portfolio against the risk-derived target.",
    },
    rationaleHe: {
      why: `ל-${f.metrics["unknownCount"]} חשבונות (${f.metrics["itemNames"]}) אין נתון רכיב צמיחה, בהיקף ${f.metrics["unknownSharePct"]}% מהשווי ההשקעתי. WealthOS לעולם לא מנחש מה בתוך עטיפה — עד שהתמהיל יוזן, ייעוץ ההקצאה חלקי${Number(f.metrics["unknownSharePct"]) > Number(f.metrics["maxPct"]) ? " והשוואת צמיחה-מול-יעד נדחית" : ""}.`,
      benefits: ["פותח (או מחדד) את המלצת ההקצאה", "הזנה חד-פעמית לכל חשבון, ניתנת לעריכה בכל עת"],
      risks: ["אין — זהו צעד השלמת נתונים, לא שינוי השקעה"],
      tradeoffs: ["כמה דקות של עיון בדוחות החשבון כדי למצוא את הרכב כל מסלול"],
      taxImplications: "אין.",
      liquidityImplications: "אין.",
      timeHorizon: "IMMEDIATE",
      sensitivity: "דוח החשבון או אתר הגוף המנהל מפרטים את הרכב הנכסים של כל מסלול.",
      alternatives: ["להשאיר לא ידוע — ניתוח ההקצאה יישאר חלקי ושמרני"],
      expectedImpact: "מנוע ההקצאה יוכל להשוות את התיק המלא מול היעד נגזר-הסיכון.",
    },
    subscores: { impact: 55, ease: 90, taxBenefit: 0, riskReduction: 20, goalContribution: 40, urgency: 60 },
    confidence: severityConfidence.NOTICE,
    evidenceItemIds: f.evidenceItemIds,
    goalTypesImproved: [],
    assumptionKeysUsed: ["allocation_mix_unknown_max_pct"],
  }),

  ALLOCATION_MIX_ESTIMATED: (f) => ({
    type: "CONFIRM_ALLOCATION_ESTIMATES",
    title: `Confirm estimated growth shares on ${f.metrics["estimatedCount"]} account(s)`,
    titleHe: `לאשר אומדני רכיב צמיחה על ${f.metrics["estimatedCount"]} חשבונות`,
    rationale: {
      why: `${f.metrics["estimatedCount"]} account(s) (${f.metrics["itemNames"]}) carry a HEURISTIC growth-share estimate (${f.metrics["estimatedSharePct"]}% of investable value). The allocation advice currently leans on these estimates — one click per account confirms or corrects them.`,
      benefits: ["Turns estimated inputs into owner-verified data", "Sharpens the allocation recommendation"],
      risks: ["None — reviewing data, not moving money"],
      tradeoffs: ["A minute per account against the statement"],
      taxImplications: "None.",
      liquidityImplications: "None.",
      timeHorizon: "IMMEDIATE",
      sensitivity: "Estimates come from track names and typical Israeli track compositions; your statement is authoritative.",
      alternatives: ["Leave as estimates — advice remains marked as estimate-based"],
      expectedImpact: "Allocation recommendations rest on confirmed data only.",
    },
    rationaleHe: {
      why: `על ${f.metrics["estimatedCount"]} חשבונות (${f.metrics["itemNames"]}) מוגדר אומדן היוריסטי של רכיב הצמיחה (${f.metrics["estimatedSharePct"]}% מהשווי ההשקעתי). ייעוץ ההקצאה נשען כרגע על האומדנים — קליק אחד לכל חשבון מאשר או מתקן אותם.`,
      benefits: ["הופך קלט משוער לנתון מאומת על ידי הבעלים", "מחדד את המלצת ההקצאה"],
      risks: ["אין — בדיקת נתונים, לא הזזת כסף"],
      tradeoffs: ["דקה לכל חשבון מול הדוח"],
      taxImplications: "אין.",
      liquidityImplications: "אין.",
      timeHorizon: "IMMEDIATE",
      sensitivity: "האומדנים נגזרים משמות מסלולים ומהרכבים טיפוסיים בישראל; הדוח שלכם הוא הקובע.",
      alternatives: ["להשאיר כאומדנים — הייעוץ יישאר מסומן כמבוסס-אומדן"],
      expectedImpact: "המלצות ההקצאה יתבססו על נתונים מאומתים בלבד.",
    },
    subscores: { impact: 40, ease: 95, taxBenefit: 0, riskReduction: 15, goalContribution: 30, urgency: 45 },
    confidence: severityConfidence.INFO,
    evidenceItemIds: f.evidenceItemIds,
    goalTypesImproved: [],
    assumptionKeysUsed: [],
  }),

  ALLOCATION_REAL_ESTATE_HIGH: (f) => ({
    type: "REBALANCE_STRUCTURAL_MIX",
    title: `Real estate is ${f.metrics["reSharePct"]}% of gross assets (threshold ${f.metrics["thresholdPct"]}%) — direct new savings to financial assets`,
    titleHe: `נדל"ן מהווה ${f.metrics["reSharePct"]}% מהנכסים (סף ${f.metrics["thresholdPct"]}%) — לנתב חיסכון חדש לנכסים פיננסיים`,
    rationale: {
      why: `Real estate makes up ${f.metrics["reSharePct"]}% of gross assets. This is a STRUCTURAL observation, not a sell instruction: a heavily property-weighted balance sheet is illiquid, concentrated in one market, and slow to adjust.`,
      benefits: ["Gradually restores flexibility and liquidity", "Reduces dependence on one local property market"],
      risks: ["None from the recommended path (it only redirects NEW savings)"],
      tradeoffs: ["Financial assets fluctuate visibly; property feels steadier than it is"],
      taxImplications: "No tax event — the recommendation avoids selling; it only directs future savings.",
      liquidityImplications: "Improves liquidity over time.",
      timeHorizon: "LONG",
      sensitivity: `Threshold is the allocation_real_estate_max_pct assumption (${f.metrics["thresholdPct"]}%) — adjust it to the household's philosophy.`,
      alternatives: ["Accept the concentration knowingly (document the decision in the journal)", "If a property sale is ever considered for OTHER reasons, revisit this balance then"],
      expectedImpact: "The financial-asset share of the balance sheet grows with every new shekel saved.",
    },
    rationaleHe: {
      why: `נדל"ן מהווה ${f.metrics["reSharePct"]}% מהנכסים ברוטו. זו תצפית מבנית, לא הוראת מכירה: מאזן מוטה-נדל"ן הוא לא נזיל, מרוכז בשוק אחד ואיטי להתאמה.`,
      benefits: ["משיב בהדרגה גמישות ונזילות", "מקטין תלות בשוק נדל\"ן מקומי אחד"],
      risks: ["אין סיכון במסלול המומלץ (הוא רק מנתב חיסכון חדש)"],
      tradeoffs: ["נכסים פיננסיים תנודתיים באופן גלוי; נדל\"ן מרגיש יציב יותר משהוא באמת"],
      taxImplications: "אין אירוע מס — ההמלצה נמנעת ממכירה; היא רק מכוונת חיסכון עתידי.",
      liquidityImplications: "משפר נזילות לאורך זמן.",
      timeHorizon: "LONG",
      sensitivity: `הסף הוא הנחת allocation_real_estate_max_pct (${f.metrics["thresholdPct"]}%) — התאימו אותו לתפיסת משק הבית.`,
      alternatives: ["לקבל את הריכוזיות במודע (לתעד את ההחלטה ביומן ההחלטות)", "אם אי-פעם תישקל מכירת נכס מסיבות אחרות — לשקלל את האיזון הזה אז"],
      expectedImpact: "חלק הנכסים הפיננסיים במאזן גדל עם כל שקל חיסכון חדש.",
    },
    subscores: { impact: 60, ease: 70, taxBenefit: 0, riskReduction: 65, goalContribution: 50, urgency: 25 },
    confidence: severityConfidence.NOTICE,
    evidenceItemIds: f.evidenceItemIds,
    goalTypesImproved: ["FINANCIAL_INDEPENDENCE"],
    assumptionKeysUsed: ["allocation_real_estate_max_pct"],
  }),
  INSURANCE_SURVIVOR_GAP: (f) => ({
    type: "CLOSE_SURVIVOR_GAP",
    title: `Increase survivor protection for ${f.metrics["memberName"]} toward ${f.metrics["months"]} months of household expenses`,
    titleHe: `להגדיל את הכיסוי לשארים עבור ${f.metrics["memberName"]} לכיוון ${f.metrics["months"]} חודשי הוצאה`,
    rationale: {
      why: `If ${f.metrics["memberName"]}'s income stops, life cover of about ${f.metrics["coverageBase"]} falls short of the roughly ${f.metrics["requiredBase"]} needed to sustain household expenses for ${f.metrics["months"]} months.`,
      benefits: ["The household can hold its standard of living if an earner is lost", "Avoids a forced sale of long-term assets or the home", "Buys time to adjust rather than deciding under pressure"],
      risks: ["Premiums are an ongoing cost", "Cover well beyond real need wastes premium"],
      tradeoffs: ["Premium spending reduces investable savings today"],
      taxImplications: "Death benefits paid to beneficiaries are generally not treated as taxable income in Israel; confirm current rules (tax registry pending owner review).",
      liquidityImplications: "A claim pays a lump sum to beneficiaries; it does not affect current household liquidity.",
      timeHorizon: "IMMEDIATE",
      sensitivity: `Sensitive to the monthly-expense estimate (${f.metrics["monthlyExpensesBase"]}) and the ${f.metrics["months"]}-month target assumption.`,
      alternatives: ["Build liquid assets that could self-insure part of the gap over time", "Reduce fixed obligations such as the mortgage so less cover is needed"],
      expectedImpact: `Bring survivor cover for ${f.metrics["memberName"]} up to roughly ${f.metrics["requiredBase"]}.`,
    },
    rationaleHe: {
      why: `אם ההכנסה של ${f.metrics["memberName"]} תיפסק, כיסוי חיים של כ-${f.metrics["coverageBase"]} נמוך מהסכום של כ-${f.metrics["requiredBase"]} הדרוש לכיסוי הוצאות משק הבית למשך ${f.metrics["months"]} חודשים.`,
      benefits: ["משק הבית יכול לשמור על רמת החיים גם באובדן מפרנס", "נמנעת מכירה כפויה של נכסים ארוכי-טווח או של הבית", "מרוויחים זמן להתארגן במקום להחליט תחת לחץ"],
      risks: ["הפרמיה היא עלות שוטפת", "כיסוי הרבה מעבר לצורך האמיתי מבזבז פרמיה"],
      tradeoffs: ["הוצאה על פרמיה מקטינה את החיסכון הפנוי להשקעה היום"],
      taxImplications: "תגמולי מוות המשולמים למוטבים בדרך כלל אינם נחשבים הכנסה חייבת בישראל; יש לאמת את הכללים הנוכחיים (רישום המס ממתין לאישור הבעלים).",
      liquidityImplications: "התביעה משלמת סכום חד-פעמי למוטבים ואינה משפיעה על נזילות משק הבית הנוכחית.",
      timeHorizon: "IMMEDIATE",
      sensitivity: `רגיש לאומדן ההוצאה החודשית (${f.metrics["monthlyExpensesBase"]}) ולהנחת היעד של ${f.metrics["months"]} חודשים.`,
      alternatives: ["לצבור נכסים נזילים שיכולים לבטח עצמית חלק מהפער עם הזמן", "להקטין התחייבויות קבועות כמו המשכנתא כדי שיידרש פחות כיסוי"],
      expectedImpact: `להעלות את הכיסוי לשארים עבור ${f.metrics["memberName"]} לכ-${f.metrics["requiredBase"]}.`,
    },
    subscores: { impact: 80, ease: 65, taxBenefit: 10, riskReduction: 92, goalContribution: 40, urgency: 80 },
    confidence: severityConfidence.WARNING,
    evidenceItemIds: f.evidenceItemIds,
    goalTypesImproved: ["LEGACY", "INHERITANCE"],
    assumptionKeysUsed: ["insurance_survivor_expense_months"],
  }),
  INSURANCE_DISABILITY_MISSING: (f) => ({
    type: "ADD_DISABILITY_COVER",
    title: `Add disability (loss-of-earning-capacity) cover for ${f.metrics["memberName"]}`,
    titleHe: `להוסיף כיסוי לאובדן כושר עבודה עבור ${f.metrics["memberName"]}`,
    rationale: {
      why: `${f.metrics["memberName"]} earns income but has no disability cover; a long illness or injury would stop earnings while household expenses continue.`,
      benefits: ["Replaces part of income if the earner cannot work", "Protects long-term savings from being drained during recovery", "Often the largest uninsured risk for a working-age earner"],
      risks: ["Premiums rise with age and health", "Definitions of disability vary between policies and matter"],
      tradeoffs: ["Premium reduces disposable income today"],
      taxImplications: "Benefit and premium treatment depend on whether cover is held standalone or through a pension arrangement; confirm current rules (tax registry pending owner review).",
      liquidityImplications: "No effect on current liquidity; pays a monthly benefit on a valid claim.",
      timeHorizon: "IMMEDIATE",
      sensitivity: "The needed level depends on the earner's income and any protection already embedded in a pension arrangement.",
      alternatives: ["Rely on disability protection embedded in a pension arrangement (verify it exists and its level)", "Self-insure through a large liquid buffer (weaker for a long disability)"],
      expectedImpact: `Put income protection in place for ${f.metrics["memberName"]}.`,
    },
    rationaleHe: {
      why: `${f.metrics["memberName"]} מפיק הכנסה אך ללא כיסוי לאובדן כושר עבודה; מחלה או פציעה ממושכת יעצרו את ההכנסה בעוד הוצאות משק הבית נמשכות.`,
      benefits: ["מחליף חלק מההכנסה כשהמפרנס אינו יכול לעבוד", "מגן על החיסכון ארוך-הטווח מפני שחיקה בתקופת ההחלמה", "לרוב הסיכון הלא-מבוטח הגדול ביותר של מפרנס בגיל העבודה"],
      risks: ["הפרמיה עולה עם הגיל ומצב הבריאות", "הגדרות אובדן הכושר משתנות בין פוליסות ומשמעותיות"],
      tradeoffs: ["הפרמיה מקטינה את ההכנסה הפנויה היום"],
      taxImplications: "המיסוי של התגמול והפרמיה תלוי אם הכיסוי עצמאי או דרך הסדר פנסיוני; יש לאמת את הכללים הנוכחיים (רישום המס ממתין לאישור הבעלים).",
      liquidityImplications: "אין השפעה על הנזילות הנוכחית; משלם קצבה חודשית בתביעה מוצדקת.",
      timeHorizon: "IMMEDIATE",
      sensitivity: "הרמה הנדרשת תלויה בהכנסת המפרנס ובכיסוי שכבר מובנה בהסדר פנסיוני.",
      alternatives: ["להסתמך על כיסוי לאובדן כושר עבודה המובנה בהסדר פנסיוני (לוודא שהוא קיים ואת רמתו)", "לבטח עצמית באמצעות כרית נזילה גדולה (חלש יותר לאובדן כושר ממושך)"],
      expectedImpact: `להסדיר הגנת הכנסה עבור ${f.metrics["memberName"]}.`,
    },
    subscores: { impact: 78, ease: 60, taxBenefit: 15, riskReduction: 90, goalContribution: 30, urgency: 82 },
    confidence: severityConfidence.WARNING,
    evidenceItemIds: f.evidenceItemIds,
    goalTypesImproved: [],
    assumptionKeysUsed: [],
  }),
  INSURANCE_MORTGAGE_LIFE_GAP: (f) => ({
    type: "CLOSE_MORTGAGE_LIFE_GAP",
    title: `Cover the mortgage against an earner's death (shortfall about ${f.metrics["shortfallBase"]})`,
    titleHe: `לכסות את יתרת המשכנתא למקרה פטירת מפרנס (פער של כ-${f.metrics["shortfallBase"]})`,
    rationale: {
      why: `Outstanding mortgage principal is about ${f.metrics["outstandingBase"]}, but mortgage-life cover is only about ${f.metrics["coverageBase"]}; survivors could be left servicing or repaying the balance.`,
      benefits: ["The home is protected from a forced sale if an earner dies", "Removes the largest single debt from the survivors' burden", "Mortgage-life cover is usually inexpensive relative to the sum insured"],
      risks: ["Cover that only decreases with the balance may lag a grace or interest-only period", "Premiums are an ongoing cost"],
      tradeoffs: ["A small ongoing premium against a large contingent liability"],
      taxImplications: "No direct tax effect on the household; confirm current rules (tax registry pending owner review).",
      liquidityImplications: "Pays down or clears the mortgage on a claim; no effect on current liquidity.",
      timeHorizon: "IMMEDIATE",
      sensitivity: `Sensitive to the current outstanding principal (${f.metrics["outstandingBase"]}), which amortizes over time.`,
      alternatives: ["Rely on general life cover sized to also clear the mortgage", "Accelerate mortgage repayment to shrink the exposure"],
      expectedImpact: `Match mortgage-life cover to the roughly ${f.metrics["outstandingBase"]} outstanding balance.`,
    },
    rationaleHe: {
      why: `יתרת קרן המשכנתא היא כ-${f.metrics["outstandingBase"]}, אך הכיסוי הביטוחי למשכנתא הוא רק כ-${f.metrics["coverageBase"]}; השארים עלולים להישאר עם החזר או פירעון היתרה.`,
      benefits: ["הבית מוגן ממכירה כפויה במקרה פטירת מפרנס", "מסיר את החוב הגדול ביותר מנטל השארים", "כיסוי ביטוח משכנתא לרוב זול ביחס לסכום המבוטח"],
      risks: ["כיסוי היורד רק עם היתרה עלול לפגר אחרי תקופת גרייס או ריבית-בלבד", "הפרמיה היא עלות שוטפת"],
      tradeoffs: ["פרמיה שוטפת קטנה מול התחייבות מותנית גדולה"],
      taxImplications: "אין השפעת מס ישירה על משק הבית; יש לאמת את הכללים הנוכחיים (רישום המס ממתין לאישור הבעלים).",
      liquidityImplications: "מפחית או מסלק את המשכנתא בתביעה; אין השפעה על הנזילות הנוכחית.",
      timeHorizon: "IMMEDIATE",
      sensitivity: `רגיש ליתרת הקרן הנוכחית (${f.metrics["outstandingBase"]}), שמופחתת עם הזמן.`,
      alternatives: ["להסתמך על ביטוח חיים כללי בהיקף שמכסה גם את המשכנתא", "להאיץ את החזר המשכנתא כדי להקטין את החשיפה"],
      expectedImpact: `להתאים את כיסוי ביטוח המשכנתא ליתרה של כ-${f.metrics["outstandingBase"]}.`,
    },
    subscores: { impact: 82, ease: 70, taxBenefit: 5, riskReduction: 88, goalContribution: 35, urgency: 78 },
    confidence: severityConfidence.WARNING,
    evidenceItemIds: f.evidenceItemIds,
    goalTypesImproved: [],
    assumptionKeysUsed: [],
  }),
  TAX_HISHTALMUT_UNDERUTILIZED: (f) => ({
    type: "MAXIMIZE_HISHTALMUT_HEADROOM",
    title: `Study fund: ${f.metrics["utilizationPct"]}% of the annual tax-exempt ceiling used for ${f.metrics["memberName"]} — ${f.metrics["monthsRemaining"]} months left`,
    titleHe: `קרן השתלמות: נוצלו ${f.metrics["utilizationPct"]}% מהתקרה השנתית הפטורה עבור ${f.metrics["memberName"]} — נותרו ${f.metrics["monthsRemaining"]} חודשים`,
    rationale: {
      why: `${f.metrics["memberName"]} has deposited about ${f.metrics["depositedBase"]} of the ${f.metrics["ceilingBase"]} annual tax-exempt study-fund ceiling; ${f.metrics["unusedBase"]} of tax-advantaged headroom is unused with ${f.metrics["monthsRemaining"]} months left in the tax year.`,
      benefits: ["Deposits within the ceiling grow fully exempt from capital-gains tax", "Full liquidity after the vesting period", "Unused annual headroom cannot be carried to next year"],
      risks: ["Funds are locked during the vesting period", "Deposits reduce disposable income now"],
      tradeoffs: ["Cash committed to the study fund is not available for other short-term uses"],
      taxImplications: "Deposits within the ceiling accrue and are withdrawn tax-free after vesting; confirm current figures (tax registry pending owner review).",
      liquidityImplications: "Reduces current liquidity; the balance becomes liquid after the vesting period.",
      timeHorizon: "IMMEDIATE",
      sensitivity: `Sensitive to the registry ceiling (${f.metrics["ceilingBase"]}) and the months remaining (${f.metrics["monthsRemaining"]}).`,
      alternatives: ["Deposit the remaining headroom before year-end as cash flow allows", "Accept partial utilization knowingly and record it in the journal"],
      expectedImpact: `Capture up to ${f.metrics["unusedBase"]} of unused tax-exempt study-fund headroom this tax year.`,
    },
    rationaleHe: {
      why: `${f.metrics["memberName"]} הפקיד כ-${f.metrics["depositedBase"]} מתוך תקרת קרן השתלמות שנתית פטורה של ${f.metrics["ceilingBase"]}; ${f.metrics["unusedBase"]} של הטבת מס אינם מנוצלים ונותרו ${f.metrics["monthsRemaining"]} חודשים בשנת המס.`,
      benefits: ["הפקדות בתוך התקרה צוברות בפטור מלא ממס רווחי הון", "נזילות מלאה לאחר תקופת הוותק", "מכסת התקרה השנתית שאינה מנוצלת אינה נשמרת לשנה הבאה"],
      risks: ["הכספים נעולים בתקופת הוותק", "הפקדות מקטינות את ההכנסה הפנויה כעת"],
      tradeoffs: ["מזומן שמופנה לקרן ההשתלמות אינו זמין לשימושים אחרים בטווח הקצר"],
      taxImplications: "הפקדות בתוך התקרה צוברות ונמשכות בפטור ממס לאחר הוותק; יש לאמת את הנתונים הנוכחיים (רישום המס ממתין לאישור הבעלים).",
      liquidityImplications: "מקטין נזילות נוכחית; היתרה הופכת לנזילה לאחר תקופת הוותק.",
      timeHorizon: "IMMEDIATE",
      sensitivity: `רגיש לתקרת הרישום (${f.metrics["ceilingBase"]}) ולמספר החודשים שנותרו (${f.metrics["monthsRemaining"]}).`,
      alternatives: ["להפקיד את יתרת המכסה לפני סוף השנה ככל שהתזרים מאפשר", "לקבל ניצול חלקי במודע ולתעד ביומן ההחלטות"],
      expectedImpact: `לנצל עד ${f.metrics["unusedBase"]} של מכסת קרן השתלמות פטורה שאינה מנוצלת בשנת המס.`,
    },
    subscores: { impact: 55, ease: 75, taxBenefit: 85, riskReduction: 20, goalContribution: 45, urgency: 60 },
    confidence: severityConfidence.NOTICE,
    evidenceItemIds: f.evidenceItemIds,
    goalTypesImproved: ["FINANCIAL_INDEPENDENCE"],
    assumptionKeysUsed: [],
  }),
  TAX_PENSION_UNDERUTILIZED: (f) => ({
    type: "MAXIMIZE_PENSION_HEADROOM",
    title: `Pension: ${f.metrics["utilizationPct"]}% of the annual tax-advantaged ceiling used for ${f.metrics["memberName"]} — ${f.metrics["monthsRemaining"]} months left`,
    titleHe: `פנסיה: נוצלו ${f.metrics["utilizationPct"]}% מהתקרה השנתית המוטבת עבור ${f.metrics["memberName"]} — נותרו ${f.metrics["monthsRemaining"]} חודשים`,
    rationale: {
      why: `${f.metrics["memberName"]} has deposited about ${f.metrics["depositedBase"]} of the ${f.metrics["ceilingBase"]} annual tax-advantaged pension ceiling; ${f.metrics["unusedBase"]} of deduction and credit headroom is unused with ${f.metrics["monthsRemaining"]} months left.`,
      benefits: ["Deposits earn income-tax deduction and credit under sections 45a/47", "Builds the retirement leg while lowering this year's tax", "Unused annual headroom does not carry forward"],
      risks: ["Locked until retirement age except in defined exceptions", "The benefit depends on the member's income versus the registry ceilings"],
      tradeoffs: ["Less flexible than taxable saving today"],
      taxImplications: "Deposits within the ceilings receive deduction and credit; growth is tax-deferred. Confirm current figures (tax registry pending owner review).",
      liquidityImplications: "Not liquid until retirement — keep other buffers in place.",
      timeHorizon: "IMMEDIATE",
      sensitivity: `Sensitive to the registry ceiling (${f.metrics["ceilingBase"]}) and the months remaining (${f.metrics["monthsRemaining"]}).`,
      alternatives: ["Top up before year-end as cash flow allows", "Use a study fund in parallel for medium-term tax-exempt saving"],
      expectedImpact: `Capture up to ${f.metrics["unusedBase"]} of unused tax-advantaged pension headroom this year.`,
    },
    rationaleHe: {
      why: `${f.metrics["memberName"]} הפקיד כ-${f.metrics["depositedBase"]} מתוך תקרת פנסיה שנתית מוטבת של ${f.metrics["ceilingBase"]}; ${f.metrics["unusedBase"]} של הטבת ניכוי וזיכוי אינם מנוצלים ונותרו ${f.metrics["monthsRemaining"]} חודשים.`,
      benefits: ["הפקדות מזכות בניכוי ובזיכוי ממס הכנסה לפי סעיפים 45א/47", "בונה את רגל הפרישה תוך הקטנת המס השנה", "מכסת התקרה השנתית שאינה מנוצלת אינה נשמרת לשנה הבאה"],
      risks: ["נעול עד גיל הפרישה למעט חריגים מוגדרים", "גובה ההטבה תלוי בהכנסת בן/בת הבית מול תקרות הרישום"],
      tradeoffs: ["גמיש פחות מחיסכון חייב במס היום"],
      taxImplications: "הפקדות בתוך התקרות מזכות בניכוי ובזיכוי; הצבירה בדחיית מס. יש לאמת את הנתונים הנוכחיים (רישום המס ממתין לאישור הבעלים).",
      liquidityImplications: "לא נזיל עד הפרישה — יש לשמור כריות ביטחון אחרות.",
      timeHorizon: "IMMEDIATE",
      sensitivity: `רגיש לתקרת הרישום (${f.metrics["ceilingBase"]}) ולמספר החודשים שנותרו (${f.metrics["monthsRemaining"]}).`,
      alternatives: ["להשלים הפקדה לפני סוף השנה ככל שהתזרים מאפשר", "להשתמש במקביל בקרן השתלמות לחיסכון פטור לטווח בינוני"],
      expectedImpact: `לנצל עד ${f.metrics["unusedBase"]} של מכסת פנסיה מוטבת שאינה מנוצלת השנה.`,
    },
    subscores: { impact: 60, ease: 70, taxBenefit: 90, riskReduction: 25, goalContribution: 60, urgency: 60 },
    confidence: severityConfidence.NOTICE,
    evidenceItemIds: f.evidenceItemIds,
    goalTypesImproved: ["RETIREMENT"],
    assumptionKeysUsed: [],
  }),
};

export interface GenerationResult {
  drafts: RecommendationDraft[];
  unmappedFindings: string[];
}

export function generateRecommendations(findings: Finding[]): GenerationResult {
  const drafts: RecommendationDraft[] = [];
  const unmapped: string[] = [];
  for (const finding of findings) {
    const generator = GENERATORS[finding.code];
    if (!generator) { unmapped.push(finding.code); continue; }
    const draft = generator(finding);
    if (!draft) continue;
    RationaleSchema.parse(draft.rationale);
    RationaleSchema.parse(draft.rationaleHe);
    const validation = validateStrategyText([
      draft.title, draft.titleHe,
      draft.rationale.why, draft.rationale.expectedImpact,
      ...draft.rationale.benefits, ...draft.rationale.alternatives, ...draft.rationale.tradeoffs,
      draft.rationaleHe.why, draft.rationaleHe.expectedImpact,
      ...draft.rationaleHe.benefits, ...draft.rationaleHe.alternatives, ...draft.rationaleHe.tradeoffs,
    ]);
    if (!validation.valid) {
      throw new Error(`PRODUCT_REFERENCE_IN_GENERATOR:${finding.code}:${validation.pattern}`);
    }
    drafts.push(draft);
  }
  return { drafts, unmappedFindings: [...new Set(unmapped)] };
}
