/** Conservative system defaults. Households override via the registry UI (new versions). */
export const DEFAULT_ASSUMPTIONS: Array<{
  key: string;
  value: unknown;
  unit: string;
  description: string;
}> = [
  { key: "expected_real_return_equity_pct", value: 4.5, unit: "PCT", description: "Long-run real return, global equities (conservative)" },
  { key: "expected_real_return_bonds_pct", value: 1.5, unit: "PCT", description: "Long-run real return, investment-grade bonds (conservative)" },
  { key: "inflation_il_pct", value: 2.5, unit: "PCT", description: "Long-run Israeli CPI assumption (BOI target band midpoint+)" },
  { key: "goal_projection_real_return_pct", value: 3.0, unit: "PCT", description: "Real return used for goal funding projections (conservative blend)" },
  { key: "mc_return_volatility_pct", value: 12, unit: "PCT", description: "Annual real-return volatility (std dev) for the Monte Carlo projector" },
  { key: "taxable_gain_fraction", value: 0.5, unit: "RATIO", description: "Assumed capital-gain fraction of a taxable withdrawal subject to CGT (tax-aware drawdown)" },
  { key: "pension_withdrawal_effective_tax_pct", value: 15, unit: "PCT", description: "Effective tax on pension withdrawals in drawdown projections (conservative; owner-reviewable)" },
  { key: "emergency_fund_months", value: 6, unit: "MONTHS", description: "Target emergency fund in months of expenses" },
  { key: "insurance_survivor_expense_months", value: 60, unit: "MONTHS", description: "Life cover for an earner should sustain household expenses for at least this many months (insurance-gap analyzer)" },
  { key: "low_confidence_threshold", value: 50, unit: "SCORE", description: "Items below this confidence are flagged in verification" },
  {
    key: "staleness_days_by_kind",
    value: { ACCOUNT: 400, REAL_ESTATE: 800, MORTGAGE: 400, LOAN: 400, CASH_FLOW: 400, INSURANCE: 800, OTHER_ASSET: 800, OTHER_LIABILITY: 800 },
    unit: "DAYS",
    description: "Valuation staleness thresholds per ledger kind",
  },
  { key: "strategy_min_completeness", value: 80, unit: "SCORE", description: "Strategy engine refuses to run below this data completeness" },
  { key: "strategy_min_confidence", value: 60, unit: "SCORE", description: "Strategy engine refuses to run below this data confidence" },
  { key: "concentration_single_asset_max_pct", value: 30, unit: "PCT", description: "Single-position share of assets that triggers a concentration warning" },
  { key: "concentration_institution_max_pct", value: 50, unit: "PCT", description: "Single-institution share of assets that triggers a notice" },
  { key: "currency_foreign_min_pct", value: 10, unit: "PCT", description: "Minimum foreign-currency share before home-bias notice" },
  { key: "currency_foreign_max_pct", value: 50, unit: "PCT", description: "Maximum foreign-currency share before excess notice" },
  { key: "management_fee_notice_pct", value: 0.8, unit: "PCT", description: "Management fee (from balance) above which fee-drag is flagged (global fallback)" },
  {
    key: "management_fee_notice_by_type",
    value: {
      PENSION_COMPREHENSIVE: 0.5,
      PENSION_GENERAL: 0.6,
      KUPAT_GEMEL: 0.7,
      GEMEL_LEHASHKAA: 0.6,
      KEREN_HISHTALMUT: 0.7,
      IRA_GEMEL: 0.7,
    },
    unit: "MAP",
    description: "Per-product-type management-fee notice thresholds (%); realistic notice levels differ by wrapper. Falls back to management_fee_notice_pct.",
  },
  { key: "mortgage_cpi_linked_max_pct", value: 60, unit: "PCT", description: "CPI-linked share of mortgage principal that triggers a notice" },
  { key: "expensive_debt_rate_pct", value: 8, unit: "PCT", description: "Debt rate above which early repayment is suggested" },
  { key: "mortgage_prime_spread_pct", value: 1.5, unit: "PCT", description: "Israeli prime rate = BOI policy rate + this spread; anchors the mortgage refinance benchmark" },
  { key: "mortgage_refinance_notice_spread_pct", value: 0.5, unit: "PCT", description: "Flag a variable/prime mortgage track when its rate exceeds the prime benchmark by this many points" },
  { key: "large_loan_notice_base", value: 100000, unit: "ILS", description: "Non-mortgage loan size that triggers review" },
  { key: "risk_loss_tolerance", value: 2, unit: "SCORE", description: "Questionnaire: tolerance for temporary losses (1=low, 2=medium, 3=high)" },
  { key: "risk_income_stability", value: 2, unit: "SCORE", description: "Questionnaire: household income stability (1=unstable, 2=mixed, 3=stable)" },
  { key: "risk_horizon_years", value: 20, unit: "YEARS", description: "Questionnaire: primary investment horizon in years" },
  { key: "allocation_rebalance_band_pct", value: 10, unit: "PCT_POINTS", description: "Allowed deviation of growth share from target before a rebalance recommendation" },
  { key: "allocation_real_estate_max_pct", value: 60, unit: "PCT", description: "Real-estate share of gross assets above which a structural notice is raised" },
  { key: "allocation_mix_unknown_max_pct", value: 50, unit: "PCT", description: "If more than this share of investable value has unknown growth mix, allocation comparison is refused (reported as data gap)" },
  { key: "drift_allocation_pct", value: 10, unit: "PCT_POINTS", description: "Deviation of growth share from the risk-derived target (percentage points) that constitutes drift (monitoring)" },
  { key: "drift_net_worth_pct", value: 10, unit: "PCT", description: "Relative net-worth change vs strategy baseline that constitutes drift (M9 monitoring)" },
  { key: "drift_liquidity_pct", value: 10, unit: "PCT_POINTS", description: "Change in liquid-asset share (percentage points) vs baseline that constitutes drift" },
  { key: "drift_concentration_pct", value: 5, unit: "PCT_POINTS", description: "Increase in single-asset concentration (percentage points) vs baseline that constitutes drift" },
  { key: "drift_goal_funding_pct", value: 10, unit: "PCT_POINTS", description: "Change in a goal's funded ratio (percentage points) vs baseline that constitutes drift" },
  {
    key: "priority_weights",
    value: { impact: 30, ease: 15, taxBenefit: 15, riskReduction: 20, goalContribution: 15, urgency: 5 },
    unit: "WEIGHTS",
    description: "Recommendation priority-score weights (sum 100); consumed by the M6 strategy engine",
  },
];
