/** Registry display grouping — key → category (UI only; the registry itself is flat). */
export const ASSUMPTION_GROUP: Record<string, string> = {
  "expected_real_return_equity_pct": "economy",
  "expected_real_return_bonds_pct": "economy",
  "inflation_il_pct": "economy",
  "goal_projection_real_return_pct": "economy",
  "mc_return_volatility_pct": "economy",
  "taxable_gain_fraction": "economy",
  "pension_withdrawal_effective_tax_pct": "economy",
  "risk_loss_tolerance": "risk",
  "risk_income_stability": "risk",
  "risk_horizon_years": "risk",
  "risk_drawdown_reaction": "risk",
  "risk_investment_experience": "risk",
  "risk_spending_flexibility": "risk",
  "allocation_rebalance_band_pct": "allocation",
  "allocation_real_estate_max_pct": "allocation",
  "allocation_mix_unknown_max_pct": "allocation",
  "emergency_fund_months": "thresholds",
  "insurance_survivor_expense_months": "thresholds",
  "concentration_single_asset_max_pct": "thresholds",
  "concentration_institution_max_pct": "thresholds",
  "currency_foreign_min_pct": "thresholds",
  "currency_foreign_max_pct": "thresholds",
  "management_fee_notice_pct": "thresholds",
  "management_fee_notice_by_type": "thresholds",
  "mortgage_cpi_linked_max_pct": "thresholds",
  "expensive_debt_rate_pct": "thresholds",
  "mortgage_prime_spread_pct": "thresholds",
  "mortgage_refinance_notice_spread_pct": "thresholds",
  "large_loan_notice_base": "thresholds",
  "low_confidence_threshold": "quality",
  "staleness_days_by_kind": "quality",
  "strategy_min_completeness": "quality",
  "strategy_min_confidence": "quality",
  "drift_allocation_pct": "drift",
  "drift_net_worth_pct": "drift",
  "drift_liquidity_pct": "drift",
  "drift_concentration_pct": "drift",
  "drift_goal_funding_pct": "drift",
  "priority_weights": "engine"
};
export const GROUP_ORDER = ["economy", "risk", "allocation", "thresholds", "quality", "drift", "engine"] as const;
